controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]
      wheel_separation: 0.5
      wheel_radius: 0.1
      use_stamped_vel: false
